export const UPDATE_SCHEDULE_REQUEST = 'UPDATE_SCHEDULE_REQUEST'
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS'
export const UPDATE_SCHEDULE_ERROR = 'UPDATE_SCHEDULE_ERROR'
export const HANDLE_SCHEDULE = 'HANDLE_SCHEDULE'